version: '3'
services:
    sos-db:
        build: https://github.com/52North/awi-nearrealtime-example-db.git#v1.0.0
        image: awi/nearrealtime-example-db:1.0.0
        ports:
        - 15432:5432
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=nearrealtime
        - POSTGRES_PASSWORD=postgres
    series-api-db:
        image: mdillon/postgis:9.6-alpine
        ports:
        - 25432:5432
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=nearrealtime
        - POSTGRES_PASSWORD=postgres
    sos:
        #build: ./awi-nrt-sos
        #build: https://github.com/52North/awi-nearrealtime-sos.git#master
        #image: awi/nearrealtime-sos:latest
        build: https://github.com/52North/awi-nearrealtime-sos.git#v1.0.0
        image: awi/nearrealtime-sos:v1.0.0
        depends_on:
        - sos-db
        ports:
        - 3000:8080
        volumes:
        - /tmp/jetty
        - ./sos-logback.xml:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/logback.xml:ro
        - ./sos-hibernate.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/hibernate.properties:ro
        - ./sos-configuration.json:/var/lib/jetty/webapps/ROOT/configuration.json:ro
    series-api:
        #build: ./awi-nrt-series-api
        build: https://github.com/52North/awi-nearrealtime-series-proxy.git#master
        image: awi/nearrealtime-series-proxy:latest
        #build: https://github.com/52North/awi-nearrealtime-series-proxy.git#v1.0.0
        #image: awi/nearrealtime-series-proxy:v1.0.0
        depends_on:
        - series-api-db
        - sos
        ports:
        - 3001:8080
        volumes:
        - ./series-api-logback.xml:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/logback.xml:ro
        - ./series-api-config-data-sources.json:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/config-data-sources.json:ro
        - ./series-api-application.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/application.properties:ro
    helgoland:
        #build: https://github.com/autermann/helgoland.git#awi
        build: ./awi-nrt-helgoland
        image: awi/nearrealtime-helgoland:latest
        depends_on:
        - series-api
        volumes:
        - ./helgoland-settings.json:/usr/src/app/dist/settings.json:ro
        ports:
        - 3002:80
    frontend:
        image: nginx:alpine
        ports:
        - 3003:80
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - helgoland
        - series-api
        - sos