version: '3'
services:
    # Postgres database with a subset of the NRT database
    sos-db:
        build: https://github.com/52North/awi-nearrealtime-example-db.git#v1.0.0
        image: awi/nearrealtime-example-db:1.0.0
        environment:
        # These have also to be configured in sos-hibernate.properties
        - POSTGRES_USER=postgres
        - POSTGRES_DB=nearrealtime
        - POSTGRES_PASSWORD=postgres
    # The Postgres database for the Series SOS Proxy
    series-api-db:
        image: mdillon/postgis:9.6-alpine
        #ports:
        #- 5432:5432
        environment:
        # These have also to be configured in series-api-application.properties
        - POSTGRES_USER=postgres
        - POSTGRES_DB=nearrealtime
        - POSTGRES_PASSWORD=postgres
    # The NRT SOS instance
    sos:
        build: https://github.com/52North/awi-nearrealtime-sos.git#v1.0.0
        image: awi/nearrealtime-sos:1.0.0
        depends_on:
        - sos-db
        ports:
        - 3000:8080
        volumes:
        # For the cache.tmp file
        - /tmp/jetty
        # Logging is currently configured to log to STDOUT
        - ./sos-logback.xml:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/logback.xml:ro
        # should contain the same credentials as the env variables of sos-db
        - ./sos-hibernate.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/hibernate.properties:ro
        # most relevant setting: service.serviceURL
        - ./sos-configuration.json:/var/lib/jetty/webapps/ROOT/configuration.json:ro
    # The NRT Series SOS Proxy instance
    series-api:
        #build: https://github.com/52North/awi-nearrealtime-series-proxy.git#master
        #image: awi/nearrealtime-series-proxy:latest
        build: https://github.com/52North/awi-nearrealtime-series-proxy.git#v1.0.3
        image: awi/nearrealtime-series-proxy:1.0.3
        depends_on:
        - series-api-db
        - sos
        ports:
        - 3001:8080
        volumes:
        # Logging is currently configured to log to STDOUT
        - ./series-api-logback.xml:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/logback.xml:ro
        # This file should configure the SOS URI. Currently set to http://sos:8080/service
        - ./series-api-config-data-sources.json:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/config-data-sources.json:ro
        # should contain the same credentials as the env variables of series-api-db
        - ./series-api-application.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/application.properties:ro
    # Helgoland in the current version, tagged from the branch feature/angularUpdate
    helgoland:
        build: https://github.com/52North/helgoland.git#v2.0.0-alpha.3
        image: 52north/helgoland:2.0.0-alpha.3
        #build: ../helgoland
        #image: 52north/helgoland:latest
        depends_on:
        - series-api
        volumes:
        # This file should configure the user-facing URI of the series API, i.e. http://localhost:3001/api/
        - ./helgoland-settings.json:/usr/share/nginx/html/assets/settings.json:ro
        ports:
        - 3002:80
    # Helgoland in the one-year-old version
    helgoland-old:
        build: https://github.com/autermann/helgoland.git#awi
        image: 52north/helgoland:awi
        depends_on:
        - series-api
        volumes:
        - ./helgoland-settings.old.json:/usr/src/app/dist/settings.json:ro
        ports:
        - 3003:8080
    # Nginx fronted to proxy all services. Not yet working
    frontend:
        image: nginx:alpine
        ports:
        - 3004:80
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - helgoland
        - series-api
        - sos
